#!/bin/sh

cd $(git rev-parse --show-toplevel)
cd docs
find * \
	-name archives-page -prune -o \
	-name Archives-page.md -prune -o \
	-type f -name '*.md' -print0 |
	xargs -0 scripts/markdown-check-links --docroot $PWD/source "$@"
